FROM apache/airflow:2.10.4

# Upgrade pip and install Spark provider
RUN pip install --upgrade pip \
    && pip install --default-timeout=120 --retries=5 apache-airflow-providers-apache-spark

# Install Python dependencies required by DAGs
RUN pip install --no-cache-dir \
    pandas \
    pyarrow \
    duckdb \
    requests \
    pendulum \
    openpyxl \
    fastparquet \
    pytest \
    apache-iceberg \
    pyspark